name: domain-adaptation
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.25.2
  - pandas=1.5.3
  - scikit-image=0.19.3
  - pillow=9.2.0
  - tqdm=4.66.1
  - requests=2.31.0
  - click=8.1.7
  - colorama=0.4.6
  - pyyaml=6.0.1
  - protobuf=4.24.4
  - python-dateutil=2.8.2
  - typing-extensions=4.7.1
  - pytorch=2.4.0
  - torchvision=0.19.0
  - torchaudio=2.4.0
  - pytorch-cuda=12.4
  - pip:
      - wandb==0.9.11
      - opencv-python==4.5.5.64
      - git+https://github.com/facebookresearch/pytorchvideo.git@main
